[2022-11-30T20:28:02.317+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: first_dag.hello manual__2022-11-30T20:28:01.426618+00:00 [queued]>
[2022-11-30T20:28:02.326+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: first_dag.hello manual__2022-11-30T20:28:01.426618+00:00 [queued]>
[2022-11-30T20:28:02.327+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-30T20:28:02.327+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-30T20:28:02.328+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-30T20:28:02.343+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): hello> on 2022-11-30 20:28:01.426618+00:00
[2022-11-30T20:28:02.348+0000] {standard_task_runner.py:55} INFO - Started process 11879 to run task
[2022-11-30T20:28:02.351+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'hello', 'manual__2022-11-30T20:28:01.426618+00:00', '--job-id', '799', '--raw', '--subdir', 'DAGS_FOLDER/***1t.py', '--cfg-path', '/tmp/tmp_ffob2uf']
[2022-11-30T20:28:02.353+0000] {standard_task_runner.py:83} INFO - Job 799: Subtask hello
[2022-11-30T20:28:02.414+0000] {task_command.py:376} INFO - Running <TaskInstance: first_dag.hello manual__2022-11-30T20:28:01.426618+00:00 [running]> on host debdf09646d4
[2022-11-30T20:28:02.487+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=hello
AIRFLOW_CTX_EXECUTION_DATE=2022-11-30T20:28:01.426618+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-30T20:28:01.426618+00:00
[2022-11-30T20:28:02.488+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-30T20:28:02.489+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo_hello']
[2022-11-30T20:28:02.499+0000] {subprocess.py:86} INFO - Output:
[2022-11-30T20:28:02.500+0000] {subprocess.py:93} INFO - /bin/bash: line 1: echo_hello: command not found
[2022-11-30T20:28:02.501+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2022-11-30T20:28:02.511+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-11-30T20:28:02.514+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=first_dag, task_id=hello, execution_date=20221130T202801, start_date=20221130T202802, end_date=20221130T202802
[2022-11-30T20:28:02.527+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 799 for task hello (Bash command failed. The command returned a non-zero exit code 127.; 11879)
[2022-11-30T20:28:02.563+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-30T20:28:02.579+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
