[2022-11-30T20:26:50.532+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: first_dag.len manual__2022-11-30T20:26:49.268335+00:00 [queued]>
[2022-11-30T20:26:50.542+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: first_dag.len manual__2022-11-30T20:26:49.268335+00:00 [queued]>
[2022-11-30T20:26:50.542+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-30T20:26:50.543+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-30T20:26:50.543+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-30T20:26:50.558+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): len> on 2022-11-30 20:26:49.268335+00:00
[2022-11-30T20:26:50.562+0000] {standard_task_runner.py:55} INFO - Started process 11814 to run task
[2022-11-30T20:26:50.565+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'len', 'manual__2022-11-30T20:26:49.268335+00:00', '--job-id', '797', '--raw', '--subdir', 'DAGS_FOLDER/***1t.py', '--cfg-path', '/tmp/tmpt6jkml0p']
[2022-11-30T20:26:50.567+0000] {standard_task_runner.py:83} INFO - Job 797: Subtask len
[2022-11-30T20:26:50.629+0000] {task_command.py:376} INFO - Running <TaskInstance: first_dag.len manual__2022-11-30T20:26:49.268335+00:00 [running]> on host debdf09646d4
[2022-11-30T20:26:50.710+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=len
AIRFLOW_CTX_EXECUTION_DATE=2022-11-30T20:26:49.268335+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-30T20:26:49.268335+00:00
[2022-11-30T20:26:50.712+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-30T20:26:50.713+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'len_csv']
[2022-11-30T20:26:50.722+0000] {subprocess.py:86} INFO - Output:
[2022-11-30T20:26:50.724+0000] {subprocess.py:93} INFO - /bin/bash: line 1: len_csv: command not found
[2022-11-30T20:26:50.724+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2022-11-30T20:26:50.734+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-11-30T20:26:50.737+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=first_dag, task_id=len, execution_date=20221130T202649, start_date=20221130T202650, end_date=20221130T202650
[2022-11-30T20:26:50.750+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 797 for task len (Bash command failed. The command returned a non-zero exit code 127.; 11814)
[2022-11-30T20:26:50.776+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-30T20:26:50.792+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
